version: '3'

services:

  db:
    image: postgres:latest
    container_name: db_app
    ports:
      - '5432:5432'
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - '5672:5672'
    env_file:
      - .env

  app:
    build:
      context: .
    container_name: fastapi_app
    command:
      - sh
      - -c
      - |
        alembic upgrade head
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload

    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./:/app

  celery:
    build:
      context: .
    command: celery -A cel:celery worker
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - ./:/app

  flower:
    build:
      context: .
    command: celery -A cel:celery flower
    ports:
      - '5555:5555'
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - celery
    volumes:
      - ./:/app